Algoritmo "idade ff"

Var

idadeAnos, idadeMeses, idadeDias, totalDias : inteiro


Inicio

 escreval("Digite quantos anos você tem:")
 leia(idadeAnos)
 escreval("Digite quantos meses:")
 leia(idadeMeses)
 escreval("Digite quantos dias:")
 leia(idadeDias)

 totalDias <- idadeDias + (idadeAnos * 365) + (idadeMeses * 30)

 escreval("Sua idade em dias é: ", totalDias)



Fimalgoritmo